<?php

namespace AppBundle\Repository;

/**
 * stuff_me_cocktailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stuff_me_cocktailRepository extends \Doctrine\ORM\EntityRepository
{
}
