<?php

namespace AppBundle\Repository;

/**
 * stuff_me_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stuff_me_userRepository extends \Doctrine\ORM\EntityRepository
{
}
